@startuml

skinparam object {
    BackgroundColor White
    ArrowColor Black
    BorderColor Black
}

object vstup {
    žádné věci
    žádní nepřátelé
}

object místnost1 {
    30 mincí
    žádní nepřátelé
}

object místnost2 {
    červený klíč
    druid (20 hp)
}

object místnost3 {
    meč, 20 mincí
    žádní nepřátelé
}

object  místnost4 {
    zelený klíč
    ork (15 hp)
}

object místnost5 {
    30 mincí
    strážce (40 hp)
}

object místnost6 {
    20 mincí, elixír života
    žádní nepřátelé
}

object místnost7 {
    10 mincí
    žádní nepřátelé
}

object místnost8 {
    10 mincí, elixír síly
}

object boss {
    40 mincí, elixír síly, modrý klíč
    big chungus (100 hp)
}

object konec {
    žádné věci
    žádní nepřátelé
}

vstup -- místnost1
místnost1 -- místnost2
místnost1 -- místnost3
místnost3 -- místnost4 #red;text:red : vyžaduje červený klíč
místnost3 -- místnost5 #green;text:green : vyžaduje zelený klíč
místnost5 -- místnost6
místnost5 -- místnost7
místnost7 -- místnost8
místnost7 -- boss
místnost7 -- konec #blue;text:blue : vyžaduje modrý klíč
@enduml
